[application]
name = "dioxus-app-codex"

[web.app]
title = "dioxus-app-codex"
port = 8080

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
